name: ddd_notes
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed_annotation: ^2.0.1
  flutter_bloc: ^8.0.1
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  google_sign_in: ^5.3.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  uuid: ^3.0.6
  auto_route: ^3.2.4
  kt_dart: ^0.10.0
  json_annotation: ^4.5.0
  rxdart: ^0.27.3
  flutter_hooks: ^0.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.0.2
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true